// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDy_GqUEon9SVA4pV5OlIAz6H2nj73Zj_I',
//     appId: '1:77506248560:android:5acc01e4724d99cb4bd9b5',
//     messagingSenderId: '77506248560',
//     projectId: 'equipment-rental-app',
//     storageBucket: 'equipment-rental-app.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyDW3GjqWz0YngkNh1ZQXrjQEiyLrVe0lPc',
//     appId: '1:77506248560:ios:cdad3d646ffb51d84bd9b5',
//     messagingSenderId: '77506248560',
//     projectId: 'equipment-rental-app',
//     storageBucket: 'equipment-rental-app.appspot.com',
//     androidClientId: '77506248560-0rcj37hip73hl5h4aht0faucqmspqmkv.apps.googleusercontent.com',
//     iosClientId: '77506248560-ajnr78mir980roshm6it9747r1qcebf7.apps.googleusercontent.com',
//     iosBundleId: 'com.yetitech.rentallpartners',
//   );
// }
